# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211130_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Телефон'),
        ),
    ]
